; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -march=vax < %s | FileCheck %s

; Multiply
define i32 @test_mul(i32 %a, i32 %b) {
  %r = mul i32 %a, %b
  ret i32 %r
}

; Signed divide
define i32 @test_sdiv(i32 %a, i32 %b) {
  %r = sdiv i32 %a, %b
  ret i32 %r
}

; Negate
define i32 @test_neg(i32 %a) {
  %r = sub i32 0, %a
  ret i32 %r
}

; OR
define i32 @test_or(i32 %a, i32 %b) {
  %r = or i32 %a, %b
  ret i32 %r
}

; XOR
define i32 @test_xor(i32 %a, i32 %b) {
  %r = xor i32 %a, %b
  ret i32 %r
}

; NOT (ones complement)
define i32 @test_not(i32 %a) {
  %r = xor i32 %a, -1
  ret i32 %r
}

; Clear (return 0)
define i32 @test_zero() {
  ret i32 0
}

; Callee-saved entry mask (value must survive call)
declare i32 @ext_func(i32)
define i32 @test_callee_saved(i32 %a, i32 %b) {
  %x = call i32 @ext_func(i32 %a)
  %r = add i32 %x, %b
  ret i32 %r
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
