; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -march=vax < %s | FileCheck %s

; i64 add with carry propagation via ADWC
define i64 @test_add64(i64 %a, i64 %b) {
  %r = add i64 %a, %b
  ret i64 %r
}

; i64 sub with borrow via SBWC
define i64 @test_sub64(i64 %a, i64 %b) {
  %r = sub i64 %a, %b
  ret i64 %r
}

; i64 bitwise AND
define i64 @test_and64(i64 %a, i64 %b) {
  %r = and i64 %a, %b
  ret i64 %r
}

; i64 bitwise OR
define i64 @test_or64(i64 %a, i64 %b) {
  %r = or i64 %a, %b
  ret i64 %r
}

; i64 constant return
define i64 @test_ret_const() {
  ret i64 42
}

; i64 left shift by constant
define i64 @test_shl64(i64 %a) {
  %r = shl i64 %a, 4
  ret i64 %r
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
