; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=vax-unknown-netbsdelf -o - %s | FileCheck %s

; Trivial function returning constant 0.
; Checks: entry mask word, clrl r0, ret.

define i32 @f() {
; CHECK-LABEL: f:
; CHECK:       .word 0
; CHECK:       clrl r0
; CHECK-NEXT:  ret
  ret i32 0
}
