; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -march=vax < %s | FileCheck %s

; Left shift by variable
define i32 @test_shl(i32 %a, i32 %b) {
  %r = shl i32 %a, %b
  ret i32 %r
}

; Left shift by constant
define i32 @test_shl_const(i32 %a) {
  %r = shl i32 %a, 4
  ret i32 %r
}

; Arithmetic right shift by variable
define i32 @test_ashr(i32 %a, i32 %b) {
  %r = ashr i32 %a, %b
  ret i32 %r
}

; Arithmetic right shift by constant
define i32 @test_ashr_const(i32 %a) {
  %r = ashr i32 %a, 4
  ret i32 %r
}

; Logical right shift by constant
define i32 @test_lshr_const(i32 %a) {
  %r = lshr i32 %a, 4
  ret i32 %r
}

; Logical right shift by variable
define i32 @test_lshr(i32 %a, i32 %b) {
  %r = lshr i32 %a, %b
  ret i32 %r
}

; Rotate left
define i32 @test_rotl(i32 %a, i32 %b) {
  %shl = shl i32 %a, %b
  %sub = sub i32 32, %b
  %shr = lshr i32 %a, %sub
  %r = or i32 %shl, %shr
  ret i32 %r
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
